document.writeln("<form action=\"http://data.zgboilers.com/post.php\" method=\"post\" onsubmit=\"this.url.value=window.top.location;\" style=\"font-size:13px;background:#9cc;padding:2px 5px;border-radius:5px\">");
document.writeln("		<strong style=\"color:red\">Quick inquiry:</strong><br/>");
document.writeln("		I need the quotation of <input type=\"hidden\" name=\"message\" value=\"I need the quotation of \"/>");
document.writeln("		<select name=\"message\" onchange=\"this.parentNode.product.value=this[this.selectedIndex].innerHTML;\" style=\"margin:0;padding:0;width:140px;\">");
document.writeln("				<option value=\" Steam boiler\">Steam Boiler</option>");
document.writeln("				<option value=\" Hot water boiler\">Hot Water Boiler</option>");
document.writeln("				<option value=\" Industrial autoclave\">Industrial Autoclave</option>");
document.writeln("		</select>");
document.writeln("		, the fuel is <input type=\"hidden\" name=\"message\" value=\", the fuel is \"/>(not for autoclave)<input type=\"text\" name=\"message\" style=\"margin:0;padding:0;width:140px\"/> ");
document.writeln("		, the pressure is <input type=\"hidden\" name=\"message\" value=\", the pressure is \"/><input type=\"text\" name=\"message\" style=\"margin:0;padding:0;width:140px;\"/>");
document.writeln("		, this capacity is <input type=\"hidden\" name=\"message\" value=\", the capacity is \"/><input type=\"text\" name=\"message\" style=\"margin:0;padding:0;width:140px;\"/>");
document.writeln("		, use for <input type=\"hidden\" name=\"message\" value=\", use for \" /><input type=\"text\" name=\"message\" style=\"margin:0;padding:0;width:140px;\"/>");
document.writeln("		. My Name is <input type=\"text\" name=\"name\" required=\"required\" style=\"margin:0;padding:0;width:140px;\"/>");
document.writeln("		, my Email is <input type=\"text\" name=\"email\"  required=\"required\" style=\"margin:0;padding:0;width:140px;\"/>");
document.writeln("		, my phone number is <input type=\"text\" name=\"tel\" style=\"margin:0;padding:0;width:140px\"/>");
document.writeln("		, Please Send the detail information for me!<input type=\"hidden\" name=\"message\" value=\", Please Send the detail information for me!\"/>");
document.writeln("		<input type=\"submit\" value=\"submit\"/>");
document.writeln("		<input type=\"hidden\" name=\"url\" value=\"\"/>");
document.writeln("		<input type=\"hidden\" name=\"product\" value=\"\"/>");
document.writeln("		<input type=\"hidden\" name=\"lang\" value=\"en\"/>");
document.writeln("</form>");
